### ISSUE TITLE
Add typescript types for the API

### ISSUE THREAD

**Issue by kshehadeh** [kmartin-215/node-pagerduty#21]
I have created type definition file for your library because I needed one.  Not sure if you want to integrate it into your library or I can add it to the DefinitelyTypes repo.  Right now I'm using it locally to my own ts application but thought it might help some other folks.

Typescript definition file:
https://github.com/NexusSwitchboard/nexus-mod-service/blob/master/src/%40types/node-pagerduty/index.d.ts

**Comment by kmartin-isp** [comment]
Thanks @kshehadeh Whichever works for you. If you want to create a PR or just add it to DefinitelyTypes.
